# Generated by Django 4.1.5 on 2023-02-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigeant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('ca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dirigeant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dirigeant')),
            ],
        ),
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('OCCASION', 'Occasion'), ('MAUVAIS ETAT', 'Mauvais Etat'), ('INUTILISABLE', 'Inutilisable')], default='NEUF', max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('LIBRE', 'Libre'), ('VENDU', 'Vendu')], default='LIBRE', max_length=100)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.magasin')),
            ],
        ),
    ]
