# Generated by Django 4.1.5 on 2023-02-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duree_minutes', models.IntegerField()),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jouer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acteur')),
                ('id_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.film')),
            ],
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('pays', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='dirigeant',
        ),
        migrations.RemoveField(
            model_name='meuble',
            name='magasin',
        ),
        migrations.DeleteModel(
            name='Dirigeant',
        ),
        migrations.DeleteModel(
            name='Magasin',
        ),
        migrations.DeleteModel(
            name='Meuble',
        ),
        migrations.AddField(
            model_name='film',
            name='id_realisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.realisateur'),
        ),
        migrations.AddField(
            model_name='film',
            name='id_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scenario'),
        ),
    ]
